### ISSUE TITLE
ActionView::Template::Error happened in ApplicationController#sitemap

### ISSUE THREAD

**Issue by ml7757** [devbootcamps/website#114]
**Message**

```
  No such file or directory @ rb_file_s_mtime - /app/app/views/programs/frontend_bootcamp.html.slim
```

**Backtrace (last 10 lines)**

```
app/views/application/sitemap.xml.erb:35:in `mtime'
app/views/application/sitemap.xml.erb:35:in `_app_views_application_sitemap_xml_erb___2026624743403051658_70217529753200'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:161:in `instrument'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/template.rb:339:in `instrument'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.7/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `block in instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
```

View on AppSignal: https://appsignal.com/development-bootcamp/sites/546a07f1776f726032a5e103/web/exceptions/ApplicationController-hash-sitemap/ActionView::Template::Error

**Comment by ml7757** [comment]
fixed it in last deploy!
